# Generated by Django 3.1.7 on 2021-03-14 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0014_auto_20210314_2329'),
        ('user_management', '0002_platformuser_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='fiat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user', to='asset_management.fiat'),
        ),
    ]
