# Generated by Django 3.1.7 on 2021-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_id', models.PositiveIntegerField()),
                ('quantity', models.FloatField(default=0)),
            ],
        ),
    ]
