# Generated by Django 3.1.7 on 2021-03-08 18:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0003_auto_20210307_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset',
            new_name='UserAsset',
        ),
    ]
