# Generated by Django 3.1.7 on 2021-03-08 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0004_auto_20210308_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_id', models.PositiveIntegerField()),
                ('logo', models.URLField()),
                ('name', models.CharField(max_length=150)),
                ('symbol', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='userasset',
            name='cmc_id',
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.URLField()),
                ('description', models.CharField(max_length=150)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='asset_management.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(related_name='asset_tags', to='asset_management.Tag'),
        ),
        migrations.AddField(
            model_name='userasset',
            name='asset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='asset_management.asset'),
        ),
    ]
