# Generated by Django 3.1.7 on 2021-03-08 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0005_auto_20210308_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='asset_management.asset'),
        ),
    ]
