# Generated by Django 3.1.7 on 2021-03-09 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0006_auto_20210308_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='asset_management.asset'),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_relations', to=settings.AUTH_USER_MODEL),
        ),
    ]
