# Generated by Django 3.1.7 on 2021-03-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0009_auto_20210310_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userasset',
            options={'ordering': ['-amount']},
        ),
        migrations.RenameField(
            model_name='userasset',
            old_name='quantity',
            new_name='amount',
        ),
    ]
