# Generated by Django 3.1.7 on 2021-03-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0014_auto_20210314_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cmc_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fiat',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
