# Generated by Django 3.1.7 on 2021-03-31 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0016_userportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userasset',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assets', to='asset_management.userportfolio'),
        ),
    ]
