# Generated by Django 3.1.7 on 2021-04-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0019_auto_20210401_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assets', to='asset_management.userportfolio'),
        ),
    ]
