# Generated by Django 3.1.7 on 2021-03-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_management', '0011_auto_20210313_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('fee', models.FloatField()),
                ('date', models.DateField()),
                ('date_time_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-date_time_add'],
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction_management.transaction')),
                ('user_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='asset_management.userasset')),
            ],
            bases=('transaction_management.transaction',),
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction_management.transaction')),
                ('user_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to='asset_management.userasset')),
            ],
            bases=('transaction_management.transaction',),
        ),
    ]
