# Generated by Django 3.1.7 on 2021-03-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date', 'date_time_add']},
        ),
    ]
